# Generated by Django 4.1.7 on 2023-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ui_name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=200)),
                ('amenities', models.CharField(max_length=1000)),
                ('is_dorm', models.BooleanField(default=False)),
                ('aws_photo_ids', models.CharField(max_length=2000, unique=True)),
            ],
        ),
    ]
