# Generated by Django 4.1.7 on 2023-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('adultsNum', models.IntegerField(default=1)),
                ('childrenNum', models.IntegerField(default=0)),
                ('roomType', models.CharField(max_length=100)),
                ('couponCode', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
    ]
