# Generated by Django 4.1.7 on 2023-03-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='roomType',
            new_name='roomName',
        ),
    ]
