# Generated by Django 4.1.7 on 2023-03-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_rename_roomtype_stay_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='couponCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
