# Generated by Django 4.1.7 on 2023-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_alter_stay_couponcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ui_name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=200)),
                ('amenities', models.CharField(max_length=1000)),
                ('is_family', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='adultsNum',
            new_name='adults_num',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='childrenNum',
            new_name='children_num',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='couponCode',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='roomName',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
