# Generated by Django 4.1.7 on 2023-04-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0004_room_rename_adultsnum_stay_adults_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_family',
            new_name='is_dorm',
        ),
        migrations.AddField(
            model_name='room',
            name='aws_photo_ids',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
