# Generated by Django 4.1.7 on 2023-04-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_rename_is_family_room_is_dorm_room_aws_photo_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
